/**
 * EU-V — shared helpers for the independent evidence browser acceptance suite.
 *
 * Contract: docs/contracts/evidence_ui_closure.md v1.0 FROZEN.
 * Write set: tests/browser/eu-acceptance-* (EU-V).
 *
 * Design rules for this suite:
 *  1. Assert observable browser behaviour (real clicks, real keyboard, real
 *     downloads), never implementation internals or source inspection.
 *  2. Every case declares a proof mode; injected transport faults are labelled
 *     and can never stand in for real API / real worker proof.
 *  3. Synthetic fixtures only; nothing real is ever uploaded or committed.
 *  4. Product bugs are reported to owners — the harness never works around
 *     them, and no assertion is weakened to make a page pass.
 */
import { execFile, execFileSync } from 'node:child_process';
import { promisify } from 'node:util';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { expect, test, type Page, type Request, type Download } from '@playwright/test';

/** Proof mode: printed in the report so nobody mistakes a stub for the real thing. */
export type ProofMode = 'REAL_API' | 'REAL_WORKER' | 'INJECTED_FAULT' | 'TRANSPORT';

/** Attach the mode to the running test so the JUnit/HTML report carries it. */
export function declareMode(mode: ProofMode, note = ''): void {
  test.info().annotations.push({
    type: 'eu-v-proof-mode',
    description: note ? `${mode} — ${note}` : mode,
  });
}

export const REPO_ROOT = path.resolve(__dirname, '..', '..');

// ---------------------------------------------------------------- fixtures ---

export interface FixtureMeta {
  path: string;
  filename: string;
  mime: string;
  source_type: string;
  size: number;
  sha256: string;
}

let fixtureCache: Record<string, FixtureMeta> | null = null;

/** Synthetic TXT/PDF/PNG fixtures, generated by the wave-standard generator. */
export function fixtures(): Record<string, FixtureMeta> {
  if (fixtureCache) return fixtureCache;
  const dir = process.env.EU_V_FIXTURE_DIR || path.join(REPO_ROOT, 'data', 'temp', 'eu-browser', 'fixtures');
  const out = execFileSync(
    path.join(REPO_ROOT, '.venv', 'bin', 'python'),
    ['scripts/eu_browser_fixtures.py', '--dir', dir, '--json'],
    { cwd: REPO_ROOT, encoding: 'utf8' },
  );
  fixtureCache = JSON.parse(out) as Record<string, FixtureMeta>;
  return fixtureCache;
}

export function fixture(kind: 'text' | 'pdf' | 'image'): FixtureMeta {
  const meta = fixtures()[kind];
  if (!meta) throw new Error(`unknown fixture kind ${kind}; got keys ${Object.keys(fixtures())}`);
  return meta;
}

export function sha256File(file: string): string {
  return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
}

// ------------------------------------------------------------- observation ---

export interface RequestLog {
  /** All requests matching the predicate, oldest first. */
  matching(pattern: RegExp): Request[];
  count(pattern: RegExp): number;
  reset(): void;
  all(): Request[];
}

/** Record every request the page makes (used for polling/duplicate detection). */
export function recordRequests(page: Page): RequestLog {
  const seen: Request[] = [];
  page.on('request', (request) => {
    if (request.url().startsWith(page.url().split('/').slice(0, 3).join('/')) ||
        request.url().includes('127.0.0.1') ||
        request.url().includes('localhost')) {
      seen.push(request);
    }
  });
  return {
    matching: (pattern) => seen.filter((r) => pattern.test(r.url())),
    count: (pattern) => seen.filter((r) => pattern.test(r.url())).length,
    reset: () => {
      seen.length = 0;
    },
    all: () => [...seen],
  };
}

/** Collect console errors and uncaught page errors for later assertions. */
export function recordErrors(page: Page): { errors: string[] } {
  const errors: string[] = [];
  page.on('console', (message) => {
    if (message.type() === 'error') errors.push(`console: ${message.text()}`);
  });
  page.on('pageerror', (error) => errors.push(`pageerror: ${error.message}`));
  return { errors };
}

/** Instrument object-URL creation/revocation (PDF preview lifecycle). */
export async function instrumentObjectUrls(page: Page): Promise<void> {
  await page.addInitScript(() => {
    const w = window as unknown as {
      __euVObjectUrls: string[];
      __euVRevokedUrls: string[];
    };
    w.__euVObjectUrls = [];
    w.__euVRevokedUrls = [];
    const create = URL.createObjectURL.bind(URL);
    const revoke = URL.revokeObjectURL.bind(URL);
    URL.createObjectURL = (obj: Blob | MediaSource) => {
      const url = create(obj);
      w.__euVObjectUrls.push(url);
      return url;
    };
    URL.revokeObjectURL = (url: string) => {
      w.__euVRevokedUrls.push(url);
      return revoke(url);
    };
  });
}

export function objectUrlState(page: Page): Promise<{ created: string[]; revoked: string[] }> {
  return page.evaluate(() => {
    const w = window as unknown as { __euVObjectUrls?: string[]; __euVRevokedUrls?: string[] };
    return { created: w.__euVObjectUrls ?? [], revoked: w.__euVRevokedUrls ?? [] };
  });
}

// ------------------------------------------------------------ interactions ---

/**
 * Upload a file the way a keyboard user would: focus the control, press a key,
 * and let the browser open the file chooser. Fails loudly if the control is not
 * focusable — that is exactly the accessibility regression EU-L must not ship.
 */
export async function uploadViaKeyboard(
  page: Page,
  selector: string,
  file: string,
): Promise<{ chooserOpened: boolean; key: 'Enter' | 'Space' }> {
  const control = page.locator(selector);
  await expect(control).toBeAttached();
  await control.focus();
  const focused = await page.evaluate(() => document.activeElement?.outerHTML ?? '');
  if (!focused) throw new Error('upload control could not receive keyboard focus');
  for (const key of ['Enter', 'Space'] as const) {
    try {
      const [chooser] = await Promise.all([
        page.waitForEvent('filechooser', { timeout: 4_000 }),
        page.keyboard.press(key),
      ]);
      await chooser.setFiles(file);
      return { chooserOpened: true, key };
    } catch {
      /* try the other activation key */
    }
  }
  return { chooserOpened: false, key: 'Enter' };
}

/** Set files on an input directly (pointer/drag-equivalent path, labelled). */
export async function uploadViaInput(page: Page, selector: string, file: string): Promise<void> {
  await page.setInputFiles(selector, file);
}

/**
 * Click something that downloads and prove the bytes are the original bytes.
 * `expectDownloadEqual` is the only acceptable proof that a download click
 * works: a preview or a 200 response is not proof.
 */
export async function expectDownloadEqual(
  page: Page,
  action: () => Promise<void>,
  expected: { path: string; sha256: string; filename?: string },
): Promise<Download> {
  const downloadPromise = page.waitForEvent('download', { timeout: 60_000 });
  await action();
  const download = await downloadPromise;
  const target = await download.path();
  expect(target, 'download produced a file').toBeTruthy();
  expect(sha256File(target!)).toBe(expected.sha256);
  if (expected.filename) expect(download.suggestedFilename()).toBe(expected.filename);
  return download;
}

// ------------------------------------------------------- fault injection -----

export interface FaultOptions {
  status?: number;
  body?: unknown;
  contentType?: string;
}

/**
 * Deterministic transport failure / status sequence, always used under
 * declareMode('INJECTED_FAULT'). Never mixed silently into a real-API case.
 */
export async function injectFailure(
  page: Page,
  urlPattern: RegExp | string,
  options: FaultOptions = {},
): Promise<() => Promise<void>> {
  await page.route(urlPattern, (route) =>
    route.fulfill({
      status: options.status ?? 500,
      contentType: options.contentType ?? 'application/json',
      body: JSON.stringify(options.body ?? { detail: 'injected failure for EU-V acceptance' }),
    }),
  );
  return () => page.unroute(urlPattern);
}

export async function injectNetworkError(
  page: Page,
  urlPattern: RegExp | string,
): Promise<() => Promise<void>> {
  await page.route(urlPattern, (route) => route.abort('failed'));
  return () => page.unroute(urlPattern);
}

export async function injectDelay(
  page: Page,
  urlPattern: RegExp | string,
  ms: number,
): Promise<() => Promise<void>> {
  await page.route(urlPattern, async (route) => {
    await new Promise((resolve) => setTimeout(resolve, ms));
    await route.continue();
  });
  return () => page.unroute(urlPattern);
}

// ------------------------------------------------------------- DB / redis ---

export const PYTHON = path.join(REPO_ROOT, '.venv', 'bin', 'python');

const SQL_SCRIPT = `
import json, sys
import psycopg2
conn = psycopg2.connect(sys.argv[1])
cur = conn.cursor()
cur.execute(sys.argv[2])
cols = [d[0] for d in cur.description] if cur.description else []
rows = [dict(zip(cols, r)) for r in cur.fetchall()]
print(json.dumps(rows, default=str))
conn.close()
`;

/**
 * Independent read of committed state. Real-worker proof needs the persisted
 * rows and status, not merely a queued job or an RQ FINISHED job.
 */
export function queryDatabaseUrl<T = Record<string, unknown>>(url: string, sql: string): T[] {
  const out = execFileSync(PYTHON, ['-c', SQL_SCRIPT, url, sql], {
    cwd: REPO_ROOT,
    encoding: 'utf8',
  });
  return JSON.parse(out) as T[];
}

export function queryDatabase<T = Record<string, unknown>>(sql: string): T[] {
  const url = process.env.EU_V_DATABASE_URL;
  if (!url) throw new Error('EU_V_DATABASE_URL is not set (start the isolated stack)');
  return queryDatabaseUrl<T>(url, sql);
}

export interface RqJobResult {
  status: string;
  result: Record<string, unknown> | null;
}

const execFileAsync = promisify(execFile);

/** Wait through RQ's supported result API without blocking the Node event loop. */
export async function waitForJobResult(jobId: string, timeoutMs = 120_000): Promise<RqJobResult> {
  const url = process.env.EU_V_REDIS_URL;
  if (!url) throw new Error('EU_V_REDIS_URL is not set (start the isolated stack)');
  const script = `
import json, sys, time
import redis
from rq.job import Job
client = redis.Redis.from_url(sys.argv[1], socket_timeout=5)
job_id, timeout = sys.argv[2], float(sys.argv[3]) / 1000
end = time.monotonic() + timeout
last = {"status": "missing", "result": None}
while time.monotonic() < end:
    try:
        job = Job.fetch(job_id, connection=client)
        status = str(job.get_status(refresh=True))
        result = job.return_value()
        if result is None:
            latest = job.latest_result()
            if latest is not None:
                result = latest.return_value
        last = {"status": status, "result": result}
        if status in ("JobStatus.FINISHED", "finished", "JobStatus.FAILED", "failed"):
            print(json.dumps(last, default=str))
            raise SystemExit(0)
    except Exception as exc:
        last = {"status": "read-error", "result": None, "error": type(exc).__name__}
    time.sleep(0.5)
print(json.dumps(last, default=str))
raise SystemExit(2)
`;
  const { stdout } = await execFileAsync(PYTHON, ['-c', script, url, jobId, String(timeoutMs)], {
    cwd: REPO_ROOT,
    encoding: 'utf8',
    timeout: timeoutMs + 10_000,
  });
  return JSON.parse(stdout) as RqJobResult;
}

/** Committed state of a source, read independently of the UI. */
export function sourceState(sourceId: string): {
  source_status?: string;
  ocr_status?: string;
  page_count?: number;
  pages?: number;
  page_texts?: string[];
} {
  const rows = queryDatabase<{
    source_status: string;
    ocr_status: string;
    page_count: number | null;
    pages: number;
    page_texts: string[];
  }>(
    `SELECT s.source_status, s.ocr_status, s.page_count,
            (SELECT count(*) FROM source_pages p WHERE p.source_id = s.id) AS pages,
            ARRAY(SELECT p.ocr_text FROM source_pages p WHERE p.source_id = s.id ORDER BY p.page_number) AS page_texts
       FROM sources s WHERE s.id = '${sourceId}'`,
  );
  return rows[0] ?? {};
}

/** Upload a uniquely named synthetic fixture and correlate the response ID. */
export async function seedSource(
  page: Page,
  kind: 'text' | 'pdf' | 'image',
): Promise<{ id: string; meta: FixtureMeta }> {
  const base = fixture(kind);
  const parsed = path.parse(base.filename);
  const filename = `${parsed.name}-${crypto.randomUUID()}${parsed.ext}`;
  const uniquePath = path.join(path.dirname(base.path), filename);
  fs.copyFileSync(base.path, uniquePath);
  const meta = { ...base, path: uniquePath, filename };

  await page.goto('/evidence');
  const uploadResponse = page.waitForResponse(
    (response) =>
      /\/api\/v1\/sources(?:\?|$)/.test(response.url()) &&
      response.request().method() === 'POST',
    { timeout: 60_000 },
  );
  await uploadViaInput(page, 'input[type=file]', meta.path);
  const response = await uploadResponse;
  expect(response.status(), 'synthetic upload response').toBeLessThan(400);
  const uploaded = (await response.json()) as { id?: string };
  expect(uploaded.id, 'upload response carries the created source ID').toBeTruthy();
  const id = String(uploaded.id);

  const row = page.locator('table tbody tr', { has: page.locator(`a[href="/evidence/${id}"]`) });
  await expect(row, `row for uploaded source ${id}`).toBeVisible({ timeout: 60_000 });
  await expect(row).toContainText(filename);
  return { id, meta };
}

/** GET a shipped endpoint through the browser context (real API, real proxy). */
export async function apiGet<T = any>(page: Page, path: string): Promise<T> {
  const response = await page.request.get(path);
  expect(response.status(), `${path} status`).toBeLessThan(400);
  return (await response.json()) as T;
}

/** POST a synthetic record through the browser context (real API). */
export async function apiPost<T = any>(page: Page, path: string, payload: unknown): Promise<T> {
  const response = await page.request.post(path, { data: payload });
  expect(response.status(), `${path} status`).toBeLessThan(400);
  return (await response.json()) as T;
}

/** Search-text helper: visible text of the region containing a source row. */
export async function rowTextFor(page: Page, title: string): Promise<string> {
  const row = page.locator('tr', { hasText: title }).first();
  await expect(row).toBeVisible();
  return (await row.innerText()).toLowerCase();
}
