#!/usr/bin/env python
"""Sprint 3 evidence-pipeline smoke — independent end-to-end verification (WS-D).

Starts the real API (uvicorn) against a scratch Postgres database and drives
the evidence flow over HTTP exactly as docs/contracts/sprint3_evidence.md §7-D
requires: bootstrap → upload text + PDF + image → source rows, sha256,
duplicate handling, page rows + OCR text where expected → include/exclude
exclusivity → matter link/unlink → reprocess (shipped worker path) without
redis → file download byte-equality.

Environment:
- DATABASE_URL (or TEST_DATABASE_URL) set → use that server (compose / CI).
- Otherwise load .env.local, else use the embedded harness scripts/agent_pg.py.

A scratch database `casevault_smoke` is (re)created and migrated from zero; it
and the scratch storage dir are dropped again on exit. The API subprocess is
forced onto a dead REDIS_URL so the enqueue-degrade path is deterministic
(a live worker could otherwise race this smoke).

Exit code 0 = all checks passed. Contract deviations (as-shipped vs v1.0)
are printed and reported in the PR; the as-shipped delta table in the
contract is authoritative (see its ⚠ SUPERSEDED note).
"""
from __future__ import annotations

import argparse
import hashlib
import os
import shutil
import signal
import socket
import subprocess
import sys
import time
from pathlib import Path

import httpx

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

SCRATCH_DB = "casevault_smoke"

TEXT_CONTENT = (
    b"NOTICE (SMOKE FIXTURE): Tenant excluded from 2F on March 3.\n"
    b"This is synthetic evidence generated by scripts/pipeline_smoke.py.\n"
)
PDF_CONTENT = b"%PDF-1.4\n%smoke-fixture\n(fake PDF bytes - classification + stub path only)\n"
PNG_CONTENT = b"\x89PNG\r\n\x1a\nsmoke-fixture-image-bytes"

# Contract v1.0 §3.2 vs as-shipped: documented deviations to report, not fail.
DEVIATIONS: list[dict[str, str]] = []


def record_deviation(section: str, expected: str, observed: str) -> None:
    DEVIATIONS.append({"section": section, "expected": expected, "observed": observed})


class Smoke:
    def __init__(self) -> None:
        self.failures = 0
        self.steps = 0

    def check(self, name: str, ok: bool, detail: str = "") -> bool:
        self.steps += 1
        if ok:
            print(f"  PASS  {self.steps:2d}. {name}")
        else:
            self.failures += 1
            print(f"  FAIL  {self.steps:2d}. {name}" + (f" — {detail}" if detail else ""))
        return ok


def load_local_env() -> None:
    try:
        from dotenv import load_dotenv

        load_dotenv(REPO_ROOT / ".env.local")
        load_dotenv(REPO_ROOT / ".env")
    except ImportError:
        pass


def resolve_server_url() -> tuple[str, str]:
    """Return (server_locator_url, how) for the Postgres server to use."""
    for var in ("DATABASE_URL", "TEST_DATABASE_URL"):
        if os.environ.get(var):
            return os.environ[var], f"env {var}"
    load_local_env()
    for var in ("DATABASE_URL", "TEST_DATABASE_URL"):
        if os.environ.get(var):
            return os.environ[var], f".env.local {var}"
    # Embedded harness (agent sandboxes without Docker).
    status = subprocess.run(
        [sys.executable, "scripts/agent_pg.py", "status"],
        capture_output=True, text=True, cwd=REPO_ROOT, check=False,
    )
    if status.returncode != 0:
        print("  (starting embedded Postgres via scripts/agent_pg.py …)")
        subprocess.run(
            [sys.executable, "scripts/agent_pg.py", "start"],
            check=True, capture_output=True, text=True, cwd=REPO_ROOT,
        )
    env = subprocess.run(
        [sys.executable, "scripts/agent_pg.py", "env"],
        check=True, capture_output=True, text=True, cwd=REPO_ROOT,
    ).stdout
    for line in env.splitlines():
        if "DATABASE_URL" in line:
            return line.split("=", 1)[1].strip().strip('"'), "agent_pg harness"
    raise SystemExit("could not resolve a Postgres URL from agent_pg.py env")


def scratch_url_from(server_url: str) -> str:
    """Same server, scratch database — as a raw string.

    Deliberately NOT sqlalchemy's URL.render_as_string(): that percent-encodes
    query values (host=%2Ftmp%2F...), and alembic's env.py feeds the URL
    through configparser interpolation, where any '%' aborts `upgrade` with
    "invalid interpolation syntax". Reported to the integrator as a finding;
    textual surgery keeps this smoke independent of that bug.
    """
    from urllib.parse import urlsplit, urlunsplit

    parts = urlsplit(server_url)
    return urlunsplit((parts.scheme, parts.netloc, f"/{SCRATCH_DB}", parts.query, ""))


def provision_scratch_db(server_url: str) -> None:
    import psycopg2

    conn = psycopg2.connect(server_url)
    conn.autocommit = True
    try:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT pg_terminate_backend(pid) FROM pg_stat_activity"
                " WHERE datname = %s AND pid <> pg_backend_pid()",
                (SCRATCH_DB,),
            )
            cur.execute(f"DROP DATABASE IF EXISTS {SCRATCH_DB}")
            cur.execute(f"CREATE DATABASE {SCRATCH_DB}")
    finally:
        conn.close()


def drop_scratch_db(server_url: str) -> None:
    import psycopg2

    conn = psycopg2.connect(server_url)
    conn.autocommit = True
    try:
        with conn.cursor() as cur:
            # the API's connection pool may still hold sessions for a moment
            # after SIGTERM — terminate them so the drop is deterministic
            cur.execute(
                "SELECT pg_terminate_backend(pid) FROM pg_stat_activity"
                " WHERE datname = %s AND pid <> pg_backend_pid()",
                (SCRATCH_DB,),
            )
            cur.execute(f"DROP DATABASE IF EXISTS {SCRATCH_DB}")
    finally:
        conn.close()


def run_migrations(surl: str) -> None:
    env = {**os.environ, "DATABASE_URL": surl}
    proc = subprocess.run(
        [sys.executable, "-m", "alembic", "-c", "apps/api/alembic.ini", "upgrade", "head"],
        cwd=REPO_ROOT, env=env, capture_output=True, text=True, check=False,
    )
    if proc.returncode != 0:
        raise SystemExit(f"alembic upgrade head failed on {SCRATCH_DB}:\n{proc.stdout}{proc.stderr}")


def free_port() -> int:
    with socket.socket() as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


def start_api(port: int, surl: str, storage_dir: Path, log_path: Path) -> subprocess.Popen:
    env = {
        **os.environ,
        "DATABASE_URL": surl,
        "LOCAL_STORAGE_ROOT": str(storage_dir),
        # Deterministic redis-degraded path: no live worker may race this smoke.
        "REDIS_URL": "redis://localhost:6399/0",
    }
    with open(log_path, "w") as log:
        return subprocess.Popen(
            [
                sys.executable, "-m", "uvicorn", "app.main:app",
                "--app-dir", "apps/api", "--host", "127.0.0.1",
                "--port", str(port), "--log-level", "warning",
            ],
            cwd=REPO_ROOT, env=env, stdout=log, stderr=subprocess.STDOUT,
        )


def wait_for_api(port: int, timeout: float | None = None) -> bool:
    # CI runners can cold-start uvicorn slowly (observed >30s on a degraded
    # runner, 2026-09-10 run 34442134277); default 90s, env-overridable.
    if timeout is None:
        timeout = float(os.environ.get("CASEVAULT_SMOKE_API_TIMEOUT", "90"))
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            if httpx.get(f"http://127.0.0.1:{port}/health", timeout=2.0).status_code == 200:
                return True
        except httpx.HTTPError:
            pass
        time.sleep(0.4)
    return False


def upload(client, filename: str, content: bytes, mime: str, **fields):
    files = {"file": (filename, content, mime)}
    data = {k: v for k, v in fields.items() if v is not None}
    return client.post("/api/v1/sources", files=files, data=data or None)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--keep", action="store_true", help="keep scratch DB + storage for debugging")
    parser.add_argument("--database-url", help="override the server locator URL")
    args = parser.parse_args()

    server_url = args.database_url or resolve_server_url()[0]
    surl = scratch_url_from(server_url)
    storage_dir = REPO_ROOT / "data" / "temp" / f"smoke-{os.getpid()}-{int(time.time())}"
    storage_dir.mkdir(parents=True, exist_ok=True)
    api_log = storage_dir / "uvicorn.log"
    port = free_port()
    server: subprocess.Popen | None = None
    smoke = Smoke()

    print("CaseVault evidence-pipeline smoke")
    print(f"  server:        {server_url}")
    print(f"  scratch DB:    {SCRATCH_DB} (migrated from zero)")
    print(f"  storage root:  {storage_dir}")
    print(f"  API:           http://127.0.0.1:{port}  (redis degraded on purpose)")

    try:
        provision_scratch_db(server_url)
        run_migrations(surl)
        server = start_api(port, surl, storage_dir, api_log)
        if not wait_for_api(port):
            print(api_log.read_text())
            raise SystemExit("API did not become healthy in time")

        with httpx.Client(base_url=f"http://127.0.0.1:{port}", timeout=30.0) as c:
            flow(c, smoke, surl)
    finally:
        if server is not None:
            server.send_signal(signal.SIGTERM)
            try:
                server.wait(timeout=10)
            except subprocess.TimeoutExpired:
                server.kill()
        if not args.keep:
            shutil.rmtree(storage_dir, ignore_errors=True)
            try:
                drop_scratch_db(server_url)
            except Exception as exc:  # noqa: BLE001 - cleanup must not mask results
                print(f"  (cleanup: could not drop {SCRATCH_DB}: {exc})")

    print()
    if DEVIATIONS:
        print(f"Contract v1.0 deviations (as-shipped; see contract delta table): {len(DEVIATIONS)}")
        for d in DEVIATIONS:
            print(f"  - §{d['section']}: expected {d['expected']} · observed {d['observed']}")
    print(
        f"RESULT: {smoke.steps - smoke.failures}/{smoke.steps} checks passed"
        f"{' — SMOKE GREEN' if smoke.failures == 0 else ' — SMOKE RED'}"
    )
    return 1 if smoke.failures else 0


def flow(c: httpx.Client, smoke: Smoke, surl: str) -> None:
    text_sha = hashlib.sha256(TEXT_CONTENT).hexdigest()

    print("\n— bootstrap (§3 preamble)")
    ws = c.get("/api/v1/workspaces/current")
    smoke.check("GET /workspaces/current -> 200", ws.status_code == 200, str(ws.status_code))
    ws_body = ws.json()
    smoke.check("workspace is CaseVault Workspace", ws_body.get("name") == "CaseVault Workspace")
    smoke.check("ai_sharing_default is no_ai", ws_body.get("ai_sharing_default") == "no_ai")

    print("\n— text upload + inline ingest (§3.1, §4.3, delta: text ingests inline)")
    r = upload(c, "notice.txt", TEXT_CONTENT, "text/plain", title="Smoke Exclusion Notice")
    smoke.check("POST /sources (text) -> 201", r.status_code == 201, r.text[:200])
    text_src = r.json()
    text_id = text_src["id"]
    smoke.check("classified source_type=text", text_src["source_type"] == "text")
    smoke.check("sha256 matches uploaded bytes", text_src["sha256"] == text_sha)
    smoke.check("file_size_bytes matches", text_src["file_size_bytes"] == len(TEXT_CONTENT))
    smoke.check("review status uploaded, no duplicate pointer",
                text_src["evidence_review_status"] == "uploaded" and text_src["duplicate_of"] is None)
    smoke.check("inline ingest: processing/ocr complete, 1 page",
                text_src["processing_status"] == "complete"
                and text_src["ocr_status"] == "complete"
                and text_src["page_count"] == 1)

    pages = c.get(f"/api/v1/sources/{text_id}/pages").json()
    smoke.check("page row with OCR text == uploaded bytes",
                len(pages) == 1 and pages[0]["ocr_text"] == TEXT_CONTENT.decode())

    f = c.get(f"/api/v1/sources/{text_id}/file")
    smoke.check("GET /sources/{id}/file byte-equality", f.status_code == 200 and f.content == TEXT_CONTENT)

    print("\n— duplicate detection (§3.1 duplicate rule)")
    r = upload(c, "notice-copy.txt", TEXT_CONTENT, "text/plain")
    smoke.check("duplicate upload still 201", r.status_code == 201, r.text[:200])
    dup = r.json()
    smoke.check("flagged evidence_review_status=duplicate", dup["evidence_review_status"] == "duplicate")
    smoke.check("duplicate_of points at first occurrence",
                (dup["duplicate_of"] or {}).get("source_id") == text_id
                and (dup["duplicate_of"] or {}).get("title") == "Smoke Exclusion Notice")

    print("\n— binary types stay queued (§4.3 classification; §5 stub)")
    r = upload(c, "summons-smoke.pdf", PDF_CONTENT, "application/pdf", title="Smoke Summons")
    smoke.check("POST /sources (pdf) -> 201", r.status_code == 201, r.text[:200])
    pdf_src = r.json()
    pdf_id = pdf_src["id"]
    smoke.check("classified source_type=pdf, queued, ocr not_started",
                pdf_src["source_type"] == "pdf"
                and pdf_src["processing_status"] == "queued"
                and pdf_src["ocr_status"] == "not_started")

    r = upload(c, "photo-smoke.png", PNG_CONTENT, "image/png")
    smoke.check("classified source_type=image", r.status_code == 201 and r.json()["source_type"] == "image")

    print("\n— reprocess (§3.2 vs delta: no endpoint; shipped path = worker)")
    r = c.post(f"/api/v1/sources/{pdf_id}/reprocess", json={"stages": ["ocr"]})
    smoke.check("POST /sources/{id}/reprocess observed 404 (documented deviation)",
                r.status_code == 404, f"status {r.status_code}")
    record_deviation("3.2", "POST /sources/{id}/reprocess -> 202 ReprocessOut",
                     "404 — shipped path is make process-jobs / RQ ingest queue")

    from workers.pipeline.jobs import process_source

    result = process_source(pdf_id, database_url=surl)
    smoke.check("worker (no redis) completes pdf via stub",
                result.get("status") == "complete" and result.get("ocr_status") == "skipped", str(result))
    after = c.get(f"/api/v1/sources/{pdf_id}").json()
    smoke.check("API reflects worker result (complete/skipped, no pages)",
                after["processing_status"] == "complete"
                and after["ocr_status"] == "skipped"
                and c.get(f"/api/v1/sources/{pdf_id}/pages").json() == [])
    smoke.check("worker job idempotent (§5)",
                process_source(pdf_id, database_url=surl).get("status") == "already_complete"
                and process_source(text_id, database_url=surl).get("status") == "already_complete")

    print("\n— lifecycle patch (§3.2 PATCH; delta: include+exclude -> 409)")
    r = c.patch(f"/api/v1/sources/{text_id}",
                json={"included_flag": True, "excluded_flag": True})
    smoke.check("include+exclude together rejected (observed 409, contract said 422)",
                r.status_code == 409, f"status {r.status_code}")
    record_deviation("3.2", "both flags true in one request -> 422", "409 (DB check constraint)")

    r = c.patch(f"/api/v1/sources/{text_id}",
                json={"excluded_flag": True, "exclusion_reason": "smoke exclusion"})
    smoke.check("exclude with reason -> 200", r.status_code == 200, r.text[:200])
    r = c.patch(f"/api/v1/sources/{text_id}",
                json={"evidence_review_status": "reviewed", "title": "Smoke Notice v2"})
    smoke.check("review status + title patch -> 200", r.status_code == 200, r.text[:200])
    smoke.check("patched values persisted",
                c.get(f"/api/v1/sources/{text_id}").json()["title"] == "Smoke Notice v2")

    print("\n— matter links (§3.2 matter-links; delta: equivalent shape)")
    matter = c.post("/api/v1/matters", json={"name": "Smoke Matter"}).json()
    r = c.post(f"/api/v1/matters/{matter['id']}/sources", json={"source_id": pdf_id})
    smoke.check("link source -> matter -> 201", r.status_code == 201, r.text[:200])
    record_deviation("3.2", "POST /sources/{id}/matter-links",
                     "POST /matters/{id}/sources (+ GET both sides, DELETE /source-matter-links/{id})")
    smoke.check("duplicate link -> 409",
                c.post(f"/api/v1/matters/{matter['id']}/sources",
                       json={"source_id": pdf_id}).status_code == 409)
    listed = c.get(f"/api/v1/matters/{matter['id']}/sources").json()
    smoke.check("matter-side listing contains source", any(s["id"] == pdf_id for s in listed))
    back = c.get(f"/api/v1/sources/{pdf_id}/matters").json()
    smoke.check("source-side listing contains matter", any(m["matter_id"] == matter["id"] for m in back))
    link_id = (c.get(f"/api/v1/matters/{matter['id']}/source-links").json() or [{}])[0].get("id")
    smoke.check("DELETE /source-matter-links/{id} -> 204",
                bool(link_id) and c.delete(f"/api/v1/source-matter-links/{link_id}").status_code == 204)
    smoke.check("unlink visible on source side",
                c.get(f"/api/v1/sources/{pdf_id}/matters").json() == [])

    print("\n— list filters + envelope (§3.2 vs delta)")
    by_type = c.get("/api/v1/sources", params={"source_type": "pdf"}).json()
    smoke.check("filter source_type=pdf", all(s["source_type"] == "pdf" for s in by_type)
                and any(s["id"] == pdf_id for s in by_type)
                and not any(s["id"] == text_id for s in by_type))
    by_review = c.get("/api/v1/sources", params={"evidence_review_status": "duplicate"}).json()
    smoke.check("filter evidence_review_status=duplicate", [s["id"] for s in by_review] == [dup["id"]])
    by_q = c.get("/api/v1/sources", params={"q": "smoke notice"}).json()
    smoke.check("title search q=smoke notice", any(s["id"] == text_id for s in by_q))
    smoke.check("list envelope is a plain JSON array (documented deviation)",
                isinstance(by_type, list))
    record_deviation("3.2", "list envelope {items,total,limit,offset}", "plain array, no pagination")
    detail = c.get(f"/api/v1/sources/{text_id}")
    smoke.check("GET /sources/{id} returns flat SourceOut (documented deviation)",
                detail.status_code == 200 and "workspace_id" in detail.json() and "source" not in detail.json())
    record_deviation("3.2", "GET /sources/{id} -> SourceDetailOut wrapper",
                     "flat SourceOut (matters via /sources/{id}/matters)")

    record_deviation("3.2", "filters q, matter, type, source_status, review_status, ocr_status, "
                     "included, excluded, limit/offset, order",
                     "q, matter_id, source_type, evidence_review_status only")


if __name__ == "__main__":
    raise SystemExit(main())
