"""phase1 foundation: users workspaces memberships settings matters links

Revision ID: 0001
Revises: 
Create Date: 2026-09-09 05:51:04.618089
"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('jurisdiction_default', sa.String(length=32), server_default='NY', nullable=False),
    sa.Column('ai_sharing_default', sa.Enum('no_ai', 'local_only', 'external_excerpts_only', 'external_selected_full_documents', name='sharing_policy_enum'), server_default='no_ai', nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matters',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('matter_type', sa.Enum('merits', 'proceeding', 'research', 'other', name='matter_type_enum'), server_default='merits', nullable=False),
    sa.Column('status', sa.Enum('active', 'planned', 'hold', 'archived', name='matter_status_enum'), server_default='active', nullable=False),
    sa.Column('theory_summary', sa.Text(), nullable=True),
    sa.Column('controlling_memo_ref', sa.Text(), nullable=True),
    sa.Column('next_work', sa.Text(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=32), server_default='NY', nullable=False),
    sa.Column('ai_sharing_policy', sa.Enum('no_ai', 'local_only', 'external_excerpts_only', 'external_selected_full_documents', name='sharing_policy_enum'), server_default='no_ai', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'slug', name='uq_matters__workspace__slug')
    )
    op.create_index('ix_matters__workspace__type__status', 'matters', ['workspace_id', 'matter_type', 'status'], unique=False)
    op.create_table('workspace_memberships',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'reviewer', 'commenter', 'viewer', 'editor_limited', name='workspace_role_enum'), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_memberships__workspace__user')
    )
    op.create_table('workspace_settings',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('settings_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.create_table('matter_links',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('from_matter_id', sa.Uuid(), nullable=False),
    sa.Column('to_matter_id', sa.Uuid(), nullable=False),
    sa.Column('link_type', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('from_matter_id <> to_matter_id', name='ck_matter_links__not_self'),
    sa.ForeignKeyConstraint(['from_matter_id'], ['matters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_matter_id'], ['matters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_matter_id', 'to_matter_id', 'link_type', name='uq_matter_links__from__to__type')
    )
    # Case-insensitive email uniqueness without CITEXT (DECISIONS 2026-09-08).
    # Extensions pgcrypto/citext intentionally NOT created: client-side UUIDs
    # make pgcrypto unnecessary and CITEXT needs contrib modules; pgvector
    # lands with the embedding decision (move to pgvector/pgvector image).
    op.execute("CREATE UNIQUE INDEX uq_users__email ON users (lower(email))")
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS uq_users__email")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matter_links')
    op.drop_table('workspace_settings')
    op.drop_table('workspace_memberships')
    op.drop_index('ix_matters__workspace__type__status', table_name='matters')
    op.drop_table('matters')
    op.drop_table('workspaces')
    op.drop_table('users')
    # Case-insensitive email uniqueness without CITEXT (DECISIONS 2026-09-08).
    # Extensions pgcrypto/citext intentionally NOT created: client-side UUIDs
    # make pgcrypto unnecessary and CITEXT needs contrib modules; pgvector
    # lands with the embedding decision (move to pgvector/pgvector image).
    op.execute("CREATE UNIQUE INDEX uq_users__email ON users (lower(email))")
    # ### end Alembic commands ###
