"""phase1 actors: actors aliases matter roles

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-09 05:51:05.861928
"""
import sqlalchemy as sa

from alembic import op

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('actor_type', sa.Enum('person', 'entity', 'court', 'agency', 'other', name='actor_type_enum'), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_actors__workspace__display_name', 'actors', ['workspace_id', 'display_name'], unique=False)
    op.create_index('ix_actors__workspace__normalized_name', 'actors', ['workspace_id', 'normalized_name'], unique=False)
    op.create_table('actor_aliases',
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('alias_text', sa.String(length=255), nullable=False),
    sa.Column('alias_type', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actor_id', 'alias_text', name='uq_actor_aliases__actor__alias')
    )
    op.create_table('matter_actor_roles',
    sa.Column('matter_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('role_label', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matter_id', 'actor_id', 'role_label', name='uq_matter_actor_roles__matter__actor__role')
    )
    # NOTE (fixed 2026-09-10): autogenerate originally emitted
    # `op.drop_index('uq_users__email')` here because the functional index
    # was missing from model metadata. That silently removed the
    # case-insensitive unique-email guarantee created in 0001. The index is
    # now declared on the User model; 0003 re-creates it where missing.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE (2026-09-10): autogenerate had emitted a stray
    # `op.create_index(op.f('uq_users__email'), 'users', …)` here. That index
    # belongs to migration 0001 and still existed, so every `alembic downgrade`
    # from this revision aborted with a duplicate-relation error. Removed by
    # the wave gate (scripts/verify_all.sh). Do not regenerate this file.
    op.drop_table('matter_actor_roles')
    op.drop_table('actor_aliases')
    op.drop_index('ix_actors__workspace__normalized_name', table_name='actors')
    op.drop_index('ix_actors__workspace__display_name', table_name='actors')
    op.drop_table('actors')
    # `sa.Enum` does not drop its Postgres type on downgrade; do it explicitly
    # so `downgrade base` -> `upgrade head` is repeatable.
    sa.Enum(name='actor_type_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
