"""phase2 sources: sources links metadata pages excerpts

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-10 04:32:47.628966

Deferred by decision: the VECTOR(1536) embedding columns from Schema
Draft 6.4 (source_pages / source_excerpts) are NOT created here — the
embedding model/provider is an open decision (handoff/DECISIONS.md).
"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.Enum('pdf', 'image', 'email', 'text', 'markdown', 'spreadsheet', 'note', 'other', name='source_type_enum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.CHAR(length=64), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('source_status', sa.Enum('primary', 'derived', 'testimony', 'working_note', 'public_record', name='source_status_enum'), server_default='derived', nullable=False),
    sa.Column('evidence_review_status', sa.Enum('uploaded', 'processing', 'reviewed', 'cited', 'included', 'excluded', 'duplicate', 'privileged', 'settlement_restricted', 'background_only', 'impeachment_only', name='evidence_review_status_enum'), server_default='uploaded', nullable=False),
    sa.Column('included_flag', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('excluded_flag', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('exclusion_reason', sa.Text(), nullable=True),
    sa.Column('authentication_notes', sa.Text(), nullable=True),
    sa.Column('restrictions_notes', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.String(length=64), server_default='queued', nullable=False),
    sa.Column('ocr_status', sa.String(length=64), server_default='not_started', nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT (included_flag AND excluded_flag)', name='ck_sources__not_included_and_excluded'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sources__sha256', 'sources', ['sha256'], unique=False)
    op.create_index('ix_sources__workspace__review_status', 'sources', ['workspace_id', 'evidence_review_status'], unique=False)
    op.create_index('ix_sources__workspace__title', 'sources', ['workspace_id', 'title'], unique=False)
    op.create_index('ix_sources__workspace__type', 'sources', ['workspace_id', 'source_type'], unique=False)
    op.create_table('source_excerpts',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('locator_text', sa.Text(), nullable=True),
    sa.Column('excerpt_text', sa.Text(), nullable=True),
    sa.Column('excerpt_type', sa.String(length=64), nullable=False),
    sa.Column('anchor_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_by', sa.String(length=16), server_default='system', nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_excerpts__source__page_start', 'source_excerpts', ['source_id', 'page_start'], unique=False)
    op.create_table('source_matter_links',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('matter_id', sa.Uuid(), nullable=False),
    sa.Column('link_reason', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'matter_id', name='uq_source_matter_links__source__matter')
    )
    op.create_table('source_metadata',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('extracted_from_filename_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('external_provenance_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('source_pages',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('page_label', sa.String(length=64), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('layout_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'page_number', name='uq_source_pages__source__page')
    )
    # Heal uq_users__email on databases where 0002's original (buggy)
    # upgrade dropped it (fixed in 0002's file; this repairs existing DBs).
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_users__email ON users (lower(email))"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_pages')
    op.drop_table('source_metadata')
    op.drop_table('source_matter_links')
    op.drop_index('ix_source_excerpts__source__page_start', table_name='source_excerpts')
    op.drop_table('source_excerpts')
    op.drop_index('ix_sources__workspace__type', table_name='sources')
    op.drop_index('ix_sources__workspace__title', table_name='sources')
    op.drop_index('ix_sources__workspace__review_status', table_name='sources')
    op.drop_index('ix_sources__sha256', table_name='sources')
    op.drop_table('sources')
    # native PG enum types survive DROP TABLE; drop them explicitly so
    # downgrade -> re-upgrade works on the same database
    # NOTE (integrator, 2026-09-10): this downgrade deliberately does NOT drop
    # uq_users__email. The index is part of the 0001 baseline (0002 only ever
    # removed it by accident — see the note in 0002's upgrade), so every
    # revision state from 0001 up must keep it; 0003's upgrade heals databases
    # that lost it. Dropping it here would silently reintroduce the bug for
    # anyone who downgrades and stops at 0002.
    sa.Enum(name='source_type_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='source_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='evidence_review_status_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
